# Generated by Django 4.0.5 on 2022-06-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='min_rent_period',
            new_name='minimum_rent_period',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='d_type',
            new_name='type',
        ),
    ]
