# Generated by Django 4.0.5 on 2022-06-08 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_product_discount_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rent_start', models.DateField()),
                ('rent_end', models.DateField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('return_date', models.DateField(null=True)),
                ('actual_cost', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
