# Generated by Django 4.0.5 on 2022-06-08 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rentproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='core.product'),
        ),
    ]
