# Generated by Django 4.0.5 on 2022-06-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_rentproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentproduct',
            name='penalty',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
